// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ClosePort():Promise<void>;

export function GetContext():Promise<context.Context>;

export function GetSerial():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function OpenPort(arg1:string):Promise<void>;
